In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("../data/creditcard_sample.csv")
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,66706.0,1.199490,0.197301,0.616923,0.554820,-0.526523,-0.785182,-0.036202,-0.070460,-0.224568,...,-0.191542,-0.597586,0.148051,0.529668,0.158453,0.064369,-0.033132,0.011166,3.59,0
1,118737.0,2.054939,-0.005134,-1.050691,0.401563,-0.047484,-1.112092,0.218426,-0.350042,0.430742,...,-0.275390,-0.616070,0.338719,0.006520,-0.288834,0.198696,-0.062744,-0.059034,1.29,0
2,67555.0,-0.943726,-0.366261,2.292128,-1.909816,-0.305247,1.903637,-0.998268,0.757791,0.170689,...,0.109482,0.651761,-0.502554,-1.659885,0.669679,-0.000532,0.228359,0.088451,2.00,0
3,6428.0,-0.960946,0.864361,1.286077,0.131434,0.630708,-0.746227,0.567456,-0.281288,0.965197,...,-0.375636,-0.589018,0.275299,-0.161066,-0.491036,-0.020583,0.150700,0.179427,5.36,0
4,159884.0,1.688499,0.142083,-2.975027,0.857739,0.752403,-1.699499,0.883376,-0.527584,-0.050348,...,0.021742,-0.179006,-0.069067,0.967166,0.029453,0.613583,-0.095408,0.044466,195.00,0

In [4]:
df.shape

(50492, 31)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50492 entries, 0 to 50491
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    50492 non-null  float64
 1   V1      50492 non-null  float64
 2   V2      50492 non-null  float64
 3   V3      50492 non-null  float64
 4   V4      50492 non-null  float64
 5   V5      50492 non-null  float64
 6   V6      50492 non-null  float64
 7   V7      50492 non-null  float64
 8   V8      50492 non-null  float64
 9   V9      50492 non-null  float64
 10  V10     50492 non-null  float64
 11  V11     50492 non-null  float64
 12  V12     50492 non-null  float64
 13  V13     50492 non-null  float64
 14  V14     50492 non-null  float64
 15  V15     50492 non-null  float64
 16  V16     50492 non-null  float64
 17  V17     50492 non-null  float64
 18  V18     50492 non-null  float64
 19  V19     50492 non-null  float64
 20  V20     50492 non-null  float64
 21  V21     50492 non-null  float64
 22  V22     50492 non-null  float64
 23  V23     50492 non-null  float64
 24  V24     50492 non-null  float64
 25  V25     50492 non-null  float64
 26  V26     50492 non-null  float64
 27  V27     50492 non-null  float64
 28  V28     50492 non-null  float64
 29  Amount  50492 non-null  float64
 30  Class   50492 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 11.9 MB

In [6]:
df.describe(include='all').T

,count,mean,std,min,25%,50%,75%,max
Time,50492.0,94841.311138,47493.217321,0.000000,54334.750000,84737.500000,139325.750000,172787.000000
V1,50492.0,-0.035635,2.084980,-46.855047,-0.928728,0.015215,1.312095,2.420346
V2,50492.0,0.025119,1.721289,-48.060856,-0.596533,0.075920,0.819162,22.057729
V3,50492.0,-0.057381,1.738835,-31.103685,-0.921974,0.167454,1.015725,4.101716
V4,50492.0,0.044276,1.486651,-5.519697,-0.826216,-0.002673,0.769941,13.129143
V5,50492.0,-0.012758,1.452318,-28.815577,-0.698951,-0.056135,0.621563,29.162172
V6,50492.0,-0.011760,1.333538,-20.869626,-0.775180,-0.278846,0.393863,21.190194
V7,50492.0,-0.051729,1.433441,-43.557242,-0.567930,0.036328,0.570005,26.249717
V8,50492.0,0.008859,1.328826,-50.420090,-0.204803,0.025071,0.331369,20.007208
V9,50492.0,-0.010958,1.144422,-13.434066,-0.647703,-0.050236,0.597968,10.370658
V10,50492.0,-0.046504,1.269664,-24.588262,-0.546766,-0.098895,0.447364,15.245686
V11,50492.0,0.026064,1.097573,-4.009307,-0.763825,-0.027516,0.754910,12.018913
V12,50492.0,-0.042684,1.208919,-18.683715,-0.412275,0.136456,0.610859,4.472921
V13,50492.0,-0.007323,0.991075,-3.961758,-0.652750,-0.026044,0.652461,4.369998
V14,50492.0,-0.057502,1.201904,-19.214325,-0.439604,0.043495,0.486423,7.754599
V15,50492.0,0.002016,0.920927,-4.498945,-0.582425,0.049936,0.658171,5.825654
V16,50492.0,-0.038728,1.005092,-14.129855,-0.482156,0.055415,0.514017,6.442798
V17,50492.0,-0.054137,1.203451,-25.162799,-0.490808,-0.069755,0.396556,8.538195
V18,50492.0,-0.016745,0.896125,-9.498746,-0.503863,-0.006495,0.497543,4.243841
V19,50492.0,0.009038,0.822491,-4.619034,-0.447915,0.006214,0.464969,5.572113
V20,50492.0,0.002999,0.760645,-23.646890,-0.212433,-0.061352,0.136501,14.935000
V21,50492.0,0.002417,0.796892,-22.889347,-0.228233,-0.025945,0.188213,27.202839
V22,50492.0,-0.000201,0.733553,-8.887017,-0.551068,0.006766,0.525697,8.361985
V23,50492.0,0.000320,0.643491,-30.269720,-0.162458,-0.009637,0.148925,17.751731
V24,50492.0,-0.001186,0.606925,-2.836627,-0.356469,0.041129,0.438423,4.016342
V25,50492.0,-0.003403,0.523209,-6.429334,-0.319083,0.015350,0.346194,5.852484
V26,50492.0,0.002159,0.483742,-1.726928,-0.327744,-0.047179,0.245012,3.517346
V27,50492.0,0.002783,0.414164,-9.543518,-0.070450,0.002154,0.094901,9.879903
V28,50492.0,0.000885,0.305807,-8.307955,-0.052208,0.011647,0.079605,15.870474
Amount,50492.0,87.204900,227.164382,0.000000,5.660000,21.990000,76.805000,8360.000000
Class,50492.0,0.009744,0.098231,0.000000,0.000000,0.000000,0.000000,1.000000

In [7]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [8]:
df['Class'].value_counts()

Class
0    50000
1      492
Name: count, dtype: int64

In [9]:
df['Class'].value_counts(normalize=True)

Class
0    0.990256
1    0.009744
Name: proportion, dtype: float64

In [10]:
X = df.drop(columns=['Class'])
y = df['Class']

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [12]:
print(y_train.mean())
print(y_test.mean())

0.00975416532567524
0.009703931082285375

In [13]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

C:\Users\Riddhi Kale\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)