In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('../data/used_car_price.csv')
df.head()

,make_year,mileage_kmpl,engine_cc,fuel_type,owner_count,price_usd,brand,transmission,color,service_history,accidents_reported,insurance_valid
0,2001,8.17,4000,Petrol,4,8587.64,Chevrolet,Manual,White,NaN,0,No
1,2014,17.59,1500,Petrol,4,5943.50,Honda,Manual,Black,NaN,0,Yes
2,2023,18.09,2500,Diesel,5,9273.58,BMW,Automatic,Black,Full,1,Yes
3,2009,11.28,800,Petrol,1,6836.24,Hyundai,Manual,Blue,Full,0,Yes
4,2005,12.23,1000,Petrol,2,4625.79,Nissan,Automatic,Red,Full,0,Yes

In [3]:
df.shape

(10000, 12)

In [5]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
make_year,10000.0,NaN,NaN,NaN,2009.2069,8.373858,1995.0,2002.0,2009.0,2016.0,2023.0
mileage_kmpl,10000.0,NaN,NaN,NaN,17.960753,5.025486,5.0,14.54,17.97,21.3525,35.0
engine_cc,10000.0,NaN,NaN,NaN,2287.13,1291.276927,800.0,1200.0,1800.0,3000.0,5000.0
fuel_type,10000,3,Petrol,4968,NaN,NaN,NaN,NaN,NaN,NaN,NaN
owner_count,10000.0,NaN,NaN,NaN,3.0035,1.418904,1.0,2.0,3.0,4.0,5.0
price_usd,10000.0,NaN,NaN,NaN,7179.754532,2795.27094,1000.0,5176.5475,6961.26,8993.7325,17647.63
brand,10000,10,Nissan,1089,NaN,NaN,NaN,NaN,NaN,NaN,NaN
transmission,10000,2,Manual,5985,NaN,NaN,NaN,NaN,NaN,NaN,NaN
color,10000,6,Gray,1705,NaN,NaN,NaN,NaN,NaN,NaN,NaN
service_history,7962,2,Full,4987,NaN,NaN,NaN,NaN,NaN,NaN,NaN
accidents_reported,10000.0,NaN,NaN,NaN,0.4922,0.694109,0.0,0.0,0.0,1.0,5.0
insurance_valid,10000,2,Yes,7934,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df.isnull().sum()

make_year                0
mileage_kmpl             0
engine_cc                0
fuel_type                0
owner_count              0
price_usd                0
brand                    0
transmission             0
color                    0
service_history       2038
accidents_reported       0
insurance_valid          0
dtype: int64

In [10]:
df_encoded = pd.get_dummies(df, columns=['fuel_type', 'brand', 'transmission', 'color', 'service_history', 'insurance_valid'], drop_first=True)

X = df_encoded.drop(columns=['price_usd'])
y = df_encoded['price_usd']

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)